name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    # @todo: this publishes to GH Pages on PR runs, fix
    #        to only run on merges to master
    branches: [ master ]
  # Allows us to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-legacy:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ["ubuntu-20.04"]
        php-versions: ["8.0"]
        phpunit-versions: ["9.6.20"]
    name: LEGACY PHP ${{ matrix.php-versions }} test on ${{ matrix.operating-system }}
    env:
      LEGACY: true
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: phpunit:${{ matrix.phpunit-versions }}
      - name: Composer Install
        run: composer install --no-dev
      - name: Run Tests
        run: make test
      - name: Run demo file
        run: php demo.php
  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ["ubuntu-latest"]
        php-versions: ["8.1", "8.2", "8.3"]
        phpunit-versions: ["latest"]
        unstable: [false]
        include:
          - php-versions: "8.4"
            operating-system: "ubuntu-latest"
            unstable: true
    env:
      COVERAGE_VERSION: "8.3"
    continue-on-error: ${{ matrix.unstable }}
    name: CURRENT PHP ${{ matrix.php-versions }} test on ${{ matrix.operating-system }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: phpunit:${{ matrix.phpunit-versions }}
      - name: Composer Install
        run: composer install --no-dev
      - name: Run Tests
        run: make test
      - name: Check test coverage
        id: test-coverage
        if: ${{ matrix.php-versions == env.COVERAGE_VERSION }}
        uses: johanvanhelden/gha-clover-test-coverage-check@v1
        with:
          percentage: "98"
          filename: "clover.xml"
      - name: Run demo file
        run: php demo.php
  # Final step to wrap up a singular protected branch action
  test-all-required:
    runs-on: ubuntu-latest
    needs: ["test-legacy", "test"]
    steps:
      - run: echo "Done!"
  publish:
    runs-on: ubuntu-latest
    needs: ["test-all-required"]
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
      - name: Publish to GH Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: demo

    
