# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-legacy:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ["ubuntu-20.04"]
        php-versions: ["8.0"]
        phpunit-versions: ["9.6.20"]
    name: LEGACY PHP ${{ matrix.php-versions }} test on ${{ matrix.operating-system }}
    env:
      LEGACY: true
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: phpunit:${{ matrix.phpunit-versions }}
      - name: Composer Install
        run: composer install --no-dev
      - name: Run Tests
        run: make test
      - name: Run demo file
        run: php demo.php
  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ["ubuntu-latest"]
        php-versions: ["8.1", "8.2"]
        phpunit-versions: ["latest"]
        unstable: [false]
        include:
          - php-versions: "8.3"
            operating-system: "ubuntu-latest"
            unstable: true
    env:
      COVERAGE_VERSION: "8.2"
    continue-on-error: ${{ matrix.unstable }}
    name: CURRENT PHP ${{ matrix.php-versions }} test on ${{ matrix.operating-system }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: phpunit:${{ matrix.phpunit-versions }}
      - name: Composer Install
        run: composer install --no-dev
      - name: Run Tests
        run: make test
      - name: Check test coverage
        id: test-coverage
        if: ${{ matrix.php-versions == env.COVERAGE_VERSION }}
        uses: johanvanhelden/gha-clover-test-coverage-check@v1
        with:
          percentage: "98"
          filename: "clover.xml"
      - name: Upload Coverage on Failure
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: clover-coverage
          path: coverage
      - name: Run demo file
        run: php demo.php
  # Final step to wrap up a singular protected branch action
  test-all-required:
    runs-on: ubuntu-latest
    needs: ["test-legacy", "test"]
    steps:
      - run: echo "Done!"
    
